apiVersion: v1
kind: Service
metadata:
  name: my-service
  annotations: # Annotationの設定 (2)
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "9102"
spec:
  selector:
    app: my-app
  ports:
  - port: 8080
    targetPort: 80
