apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: mattormost-pdb
spec:
  maxUnavailable: 1 # (1) 動作しないことを許容する最大のPodの数または割合
  selector: #(2) 対象のPodを選択するための指定
    matchLabels:
      app: mattermost
