apiVersion: batch/v1
kind: Job
metadata:
    name: job-test
spec:
    completions: 3
    template:
        metadata:
            labels:
                app: job-test
        spec:
            containers:
                - name: busybox
                  image: busybox
                  args:
                      - /bin/sh
                      - -c
                      - echo hello;sleep 30;echo world
