apiVersion: v1
kind: Pod
metadata:
    name: multi-container
spec:
    containers:
        - name: multi-container1
          image: busybox
          command:
              - "/bin/sh"
              - -c 
              - "echo 'hello'; sleep 3600"
        - name: multi-container2
          image: busybox
          command:
              - ls
