apiVersion: v1
kind: PersistentVolume
metadata:
    name: backup
spec:
    capacity:
        storage: 10Gi
    accessModes:
        - ReadWriteMany
    persistentVolumeReclaimPolicy: Retain
    storageClassName: nfs
    mountOptions:
        - hard
    nfs:
        path: /System/Volumes/Data/Users/yumatsud/nfs_share
        server: 192.168.64.1
