apiVersion: v1
kind: Pod
metadata:
  name: secret-env
spec:
  containers:
  - name: nginx
    image: k8spracticalguide/nginx:1.15.5
    ports:
    - containerPort: 80
    env:
    - name: SECRET_PASSWORD # 設定する環境変数名
      valueFrom:
        secretKeyRef: # 環境変数の値として利用するSecretのキーの参照 (2)
          name: mysecret # Secret名を指定する
          key: password # Secretのキー名を指定
