apiVersion: v1
kind: Pod
metadata:
  name: secret-volume
spec:
  containers:
  - name: nginx
    image: k8spracticalguide/nginx:1.15.5
    ports:
    - containerPort: 80
    volumeMounts:
    - name: mysecret-volume # 下記の Volume 名と一致しなければならない
      readOnly: true
      mountPath: /secrets/mysecret
  volumes:
    - name: mysecret-volume
      secret: # Volumeとして投入するSecretの設定 (1)
        secretName: mysecret # Secret 名と一致しなければならない
