apiVersion: v1
kind: Pod
metadata:
  name: cm-env
spec:
  containers:
  - name: nginx
    image: k8spracticalguide/nginx:1.15.5
    ports:
    - containerPort: 80
    env: # コンテナで設定される環境変数のリスト (4)
    - name: DATABASE_HOST # 設定する環境変数名
      valueFrom:
        configMapKeyRef:
          name: my-cm # ConfigMap名を指定
          key: DATABASE_HOST # ConfigMapのキー名を指定
